# ── DATABASE ──
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:jerm12345}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

# ── JPA ──
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}

# ── JWT ──
app.jwt.secret=${JWT_SECRET:SuperSecretKey12345678901234567890_change_in_production}
app.jwt.expiration-ms=86400000

# ── OAuth2 ──
spring.security.oauth2.client.registration.google.client-id=806645108353-9m86utrh0cabhto658b9d9lq8jjut32t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# ── Server ──
server.port=${PORT:8080}
app.frontend-url=https://quanlysinhvien-o3wo.onrender.com